### ISSUE TITLE
UseRoaming is not available in Mac OSX Sierra

### ISSUE THREAD

**Issue by Kjir** [dolmen/github-keygen#31]
When generating a key/configuration using `github-keygen` on OS X Sierra the SSH connections to github will give the following warning:

```
$ git pull
/Users/stephanebisinger/.ssh/config: line 41: Bad configuration option: useroaming
/Users/stephanebisinger/.ssh/config: terminating, 1 bad configuration options
```

**Comment by dolmen** [comment]
Short time workaround: just comment the option in `~/.ssh/config`

`github-keygen` has builtin detection of the options supported by the local OpenSSH installation: it parses the local `ssh_config` man page. But `UseRoaming` is a difficult option to handle automatically as it was undocumented option (so not present in the manpage) but a potential security issue if enabled (if you fear that GitHub may attack you) which is the default in OpenSSH 5.4 to 7.1.
`UseRoaming` is still recognized (but deprecated, so ignored) in the version I have (7.2p2).

Could you give me the exact version of OpenSSH bundled on Sierra?

**Comment by dolmen** [comment]
I've published release 1.301 that is removes `UseRoaming` if OpenSSH 7.3+.

**Comment by elyscape** [comment]
@dolmen macOS Sierra has OpenSSH 7.2p2. That being said, Ubuntu 16.04 LTS has OpenSSH 7.2p2 and does support the `UseRoaming` option.

One way to check for this might be to shell out to `ssh` and checking the stderr, like so:
```shellsession
removed:~ elyscape$ # macOS Sierra
removed:~ elyscape$ ssh -V
OpenSSH_7.2p2, LibreSSL 2.4.1
removed:~ elyscape$ ssh -o UseRoaming=no
command-line: line 0: Bad configuration option: useroaming
```
```shellsession
elyscape@removed:~$ # Ubuntu 16.04 LTS
elyscape@removed:~$ ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
elyscape@removed:~$ ssh -o UseRoaming=no
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

**Comment by keith-rollin** [comment]
Thanks, @elyscape. I just ran into this problem, too. I hopped up here to report it and found that you were all over it. So that was great!

**Comment by dolmen** [comment]
I think I will just add a special case for OpenSSH 7.2 on Sierra.
Could you give me the output of this command on Sierra?
```
$ perl -E 'say $^O'
```

**Comment by keith-rollin** [comment]
$ perl -E 'say $^O'
darwin

**Comment by keith-rollin** [comment]
And for grins:

$ uname -s
Darwin

**Comment by keith-rollin** [comment]
And if that's not incompatible enough for you:

$ sw_vers -productName
Mac OS X

**Comment by dolmen** [comment]
Release v1.302 is available.
