### ISSUE TITLE
Remove support for hmac-ripemd160 MAC

### ISSUE THREAD

**Issue by keith-rollin** [dolmen/github-keygen#38]
SSH no longer supports this MAC:

https://www.openssh.com/txt/release-7.6
-----
...
 * ssh(1)/sshd(8): remove support for the hmac-ripemd160 MAC.

...

**Comment by dolmen** [comment]
This issue is supposed to have been fixed with [v1.303](https://github.com/dolmen/github-keygen/releases/tag/v1.303) which re-enabled detection of algorithms supported by your OpenSSH client to disable unsupported ones.
